version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: studentcouncil_db
    environment:
      POSTGRES_DB: studsovet
      POSTGRES_USER: studsovet_admin
      POSTGRES_PASSWORD: Demonrux201
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: .
    container_name: studentcouncil_backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=studsovet;Username=studsovet_admin;Password=Demonrux201
    depends_on:
      - postgres
    volumes:
      - backend_wwwroot:/app/wwwroot
    restart: unless-stopped

  frontend:
    build: ./StudentCouncil.Frontend
    container_name: studentcouncil_frontend
    ports:
      - "8081:80"   # ← другой порт, не 80
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  backend_wwwroot: