server {
    listen 80;
    server_name _;
    
    types {
        image/gif gif;
        image/jpeg jpg jpeg;
        image/png png;
        image/svg+xml svg;
        audio/mpeg mp3;
        video/mp4 mp4;
        application/pdf pdf;
    }
    default_type application/octet-stream;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /avatars/ {
        proxy_pass http://backend:8080/avatars/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}