server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    types {
        text/html html;
        text/css css;
        application/javascript js;
        image/svg+xml svg;
    }
    default_type text/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
    }

    location /avatars/ {
        proxy_pass http://backend:8080/avatars/;
        proxy_set_header Host $host;
    }
}